unique_name: ColonListCriterion_t10k
output_dir: ./output/datasets/
base_datasets:
  - C4
  - Pile
base_datasets_dir: ./base_datasets
data_split: train
criteria:
  - ColonListCriterion
target_hits: 10000