unique_name: ExamplesStringsCriterion_1k
output_dir: ./output/datasets/
base_datasets:
  - Pile
base_datasets_dir: ./base_datasets
data_split: validation # Use smaller data split for small tests
criteria:
  - ExamplesStringsCriterion
max_documents: 1000