unique_name: ExamplesStringsCriterion_t5k
output_dir: ./output/datasets/
base_datasets:
  - C4
  - Pile
base_datasets_dir: ./base_datasets
data_split: train
criteria:
  - ExamplesStringsCriterion
target_hits: 5000