unique_name: ExamplesStringsCriterion_t200
output_dir: ./output/datasets/
base_datasets:
  - C4
  - Pile
base_datasets_dir: ./base_datasets
data_split: validation # Use smaller data split for small tests
criteria:
  - ExamplesStringsCriterion
target_hits: 200