unique_name: QuestionAnswerStringsV2Criterion_val_t1k
output_dir: ./output/datasets/
base_datasets:
  - C4
  - Pile
base_datasets_dir: ./base_datasets
data_split: validation
criteria:
  - QuestionAnswerStringsV2Criterion
target_hits: 1000