unique_name: QuestionAnswerStringsV2Criterion_t10M
output_dir: ./output/datasets/
base_datasets:
  - C4
  - Pile
base_datasets_dir: ./base_datasets
data_split: train
criteria:
  - QuestionAnswerStringsV2Criterion
target_hits: 10000000